on:
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: 'Install dependencies'
        run: npm clean-install
      - name: 'Lint'
        run: npm run lint
      - name: 'Check formatting'
        run: npm run format
      - name: 'Test'
        run: npm test
